# Generated by Django 4.1 on 2022-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
